name: models
version: 0.0.1+1

description: A package to define shared data models.

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  cloud_firestore: ^6.1.1
dev_dependencies:
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
