name: firebase_services
description: A new Flutter package to provide Firebase services.
version: 0.0.1+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  cloud_firestore: ^6.1.1
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
dev_dependencies:
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
