name: localization
version: 1.0.0+1

description: A package to handle i18n with English and Burmese support.

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.4
dev_dependencies:
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5

flutter:
  generate: true
