name: core
version: 1.0.0+1

description: A package to include shared logic and utilities.

environment:
  sdk: ^3.10.7

dependencies:
  audio_session: ^0.2.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_riverpod: ^3.1.0
  just_audio: ^0.10.5
  riverpod_annotation: ^4.0.0
dev_dependencies:
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
