name: creator_resource_hub_mobile
description: A mobile app for managing and accessing creator resources.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  cloud_firestore: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.4

  core:
    path: ../../packages/core
  models:
    path: ../../packages/models
  localization:
    path: ../../packages/localization
  firebase_services:
    path: ../../packages/firebase_services
    
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  google_sign_in: ^7.2.0
  just_audio: ^0.10.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Regular.ttf
        - asset: assets/fonts/GentiumPlus-Italic.ttf
          style: italic
        - asset: assets/fonts/GentiumPlus-Bold.ttf
          weight: 700
        - asset: assets/fonts/GentiumPlus-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-2.5.3_Regular.ttf
        - asset: assets/fonts/Pyidaungsu-2.5.3_Bold.ttf
          weight: 700
        - asset: assets/fonts/Pyidaungsu-2.5.3_Numbers.ttf

dev_dependencies:
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
